---
- name: This sets up an httpd webserver
  hosts: Test
  become: yes
  tasks:
    - name: Install apache packages
      apt:
        name: apache2
        state: latest

    - name: ensure httpd is running
      service:
        name:  apache2
        state: started
        
    - name: Test Html Page
      copy:
        content: "Ansibel using Jenkins\n"
        dest: /var/www/html/index.html
   
