---
- name: This sets up an httpd webserver
  hosts: Test
  become: yes
  tasks:
    - name: Install apache packages
      apt:
        name: appache2
        state: latest

    - name: ensure httpd is running
      service:
        name:  apache2
        state: started
    - debub:
        msg : the service is running
